### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by syedhamidali** [mabelcalim/waipy#25] opened 2021-06-10 06:35 UTC
![image](https://user-images.githubusercontent.com/35923822/121476327-270fb780-c9e4-11eb-91cb-bdf1384f171e.png)

**Comment by Semirarmis** [comment] 2021-07-16 19:58
Same error here :/

**Comment by GallowayJ** [comment] 2021-08-29 11:11
@syedhamidali Please could you close this issue? I've opened a new issue referencing this one with what I think is root cause.

**Comment by syedhamidali** [comment] 2021-08-29 11:56
Sure

**Closed** 2021-08-29 11:56 UTC
